#!/bin/bash

#------------------------------------------------------------------------------

function source_if { test -e "$1" && source "$@"; }

# from mshex/functions/hdirname.sh

# readlink -f
function hdirname/readlink {
  local path="$1"
  case "$OSTYPE" in
  (cygwin|linux-gnu)
    # 少なくとも cygwin, GNU/Linux では readlink -f が使える
    PATH=/bin:/usr/bin readlink -f "$path" ;;
  (darwin*|*)
    # Mac OSX には readlink -f がない。
    local PWD="$PWD" OLDPWD="$OLDPWD"
    while [[ -h $path ]]; do
      local link="$(PATH=/bin:/usr/bin readlink "$path" || true)"
      [[ $link ]] || break

      if [[ $link = /* || $path != */* ]]; then
        # * $link ~ 絶対パス の時
        # * $link ~ 相対パス かつ ( $path が現在のディレクトリにある ) の時
        path="$link"
      else
        local dir="${path%/*}"
        path="${dir%/}/$link"
      fi
    done
    echo -n "$path" ;;
  esac
}

## @fn hdirname/impl file defaultValue
## @param[in] file
## @param[in] defaultValue
## @var[out] _ret
function hdirname {
  if [[ $1 == -v ]]; then
    # hdirname -v var file defaultValue
    eval '
      '$2'="$3"
      [[ -h ${'$2'} ]] && '$2'=$(hdirname/readlink "${'$2'}")

      if [[ ${'$2'} == */* ]]; then
        '$2'="${'$2'%/*}"
        : "${'$2':=/}"
      else
        '$2'="${4-$PWD}"
      fi
    '
  elif [[ $1 == -v* ]]; then
    hdirname -v "${1:2}" "${@:2}"
  else
    local ret
    hdirname -v ret "$@"
    echo -n "$ret"
  fi
}

#------------------------------------------------------------------------------
# create library

if test $# -eq 0; then
  echo "usage: cxxar NAME [objectfiles...]" > /dev/stderr
  echo "  the target library is libNAME.a or NAME.lib" > /dev/stderr
  exit 1
fi

#------------------------------------------------------------------------------
# source

: ${MWGDIR:=$HOME/.mwg}
hdirname -v CXXDIR "${BASH_SOURCE:-$0}" "$MWGDIR/share/mcxx"
export CXXDIR

source "$CXXDIR/cxx_pref-get.sh"
source_if "$CXXDIR2/config.src"
if [[ -f "$CXXDIR2/cxxar" ]]; then
  "$CXXDIR2/cxxar" "$@"
else
  "$CXXDIR/cxxar-default.sh" "$@"
fi
