#!/bin/bash
#
# echox-1.0.0 - echo extensions for bash
#
#   copyright 2010-2012, Koichi Murase, myoga.murase@gmail.com
#
#   file:  $HOME/.mwg/echox
#   usage: source $HOME/.mwg/echox
# 
#
# ChangeLog
#
# 2012-10-15, KM, echox-1.0.0
#   * version 番号その他を付ける事に。
# 2012-10-02, KM
#   * echor がデフォルトの値を返した時に exit 1 になってしまうのを修正
# 2012-05-24, KM
#   * escape sequence による色付けを修正
# 2012-04-30, KM
#   * 引数判定で引数を test のオプションと間違えるバグを修正
# 2011-10-23, KM
#   * インデント push/pop 機能
# 2011-04-07, KM
#   * tkyntn に移植
# 2010-09-26, KM
#   * echo に対する引数 (-n, -e) を受け取れる様に修正
# 2010-09-22, KM
#   * 作成
#
##-------------------------------------------------------------------------------
#  utils
#-------------------------------------------------------------------------------
mwg_echox_prog="$0"
mwg_echox_indent=0
mwg_echox_indent_text=''
mwg_echox_indent_stk[0]=''

function echox.initialize {
  if [[ -t 1 ]]; then
    local fColorAuto=1
  else
    local fColorAuto=
  fi
  local fColor="$fColorAuto"

  while (($#)); do
    local arg="$1"
    shift
    case "$arg" in
    (--color|--color=always)
      fColor=1 ;;
    (--color=none|--color=never)
      fColor= ;;
    (--color=auto)
      fColor="$fColorAuto" ;;
    (*)
      echo "echox.initialize! unrecognized option '$arg'" >&2
      return ;;
    esac
  done

  if [[ $fColor ]]; then
    mwg_term_sgr0='[m'
    mwg_term_setfg='[32m'
    mwg_term_setfb='[34m'
    mwg_term_setfm='[35m'
    mwg_term_setfK='[90m'
    mwg_term_setfR='[91m'
    mwg_term_setfB='[94m'
  else
    mwg_term_sgr0=
    mwg_term_setfg=
    mwg_term_setfb=
    mwg_term_setfm=
    mwg_term_setfK=
    mwg_term_setfR=
    mwg_term_setfB=
  fi
}
echox.initialize "$@"

declare -i mwg_bash=$((${BASH_VERSINFO[0]}*10000+${BASH_VERSINFO[1]}*100+${BASH_VERSINFO[2]}))

function echox {
  if test "x${1:0:2}" == x-e -o "x${1:0:2}" == x-n; then
    local opt="$1"
    shift
  else
    local opt=''
  fi
  echo $opt "$mwg_term_setfB$mwg_echox_prog\$$mwg_term_sgr0 $mwg_echox_indent_text$mwg_term_setfb$*$mwg_term_sgr0"
}
function echoe {
  if test "x${1:0:2}" == x-e -o "x${1:0:2}" == x-n; then
    local opt="$1"
    shift
  else
    local opt=''
  fi
  echo $opt "$mwg_term_setfR$mwg_echox_prog!$mwg_term_sgr0 $mwg_echox_indent_text$*"
}
function echom {
  if test "x${1:0:2}" == x-e -o "x${1:0:2}" == x-n; then
    local opt="$1"
    shift
  else
    local opt=''
  fi
  echo $opt "$mwg_term_setfb$mwg_echox_prog:$mwg_term_sgr0 $mwg_echox_indent_text$*"
}
function echor {
  local var="$1"
  local msg="$mwg_term_setfb$mwg_echox_prog: $mwg_echox_indent_text$mwg_term_setfg$2$mwg_term_sgr0"
  local def="$3"
  test -n "$def" && msg="$msg [$mwg_term_setfm$def$mwg_term_sgr0]"

  if test "$mwg_bash" -ge 40000; then
    read -e -i "$def" -p "$msg$mwg_term_setfb ? $mwg_term_sgr0" "$var"
  else
    read -e           -p "$msg$mwg_term_setfb ? $mwg_term_sgr0" "$var"
  fi

  if test -n "$def"; then
    eval ': ${'"$var"':=$def}'
  fi
}

function echox_push {
  local indent="$1"
  if test -z "$indent"; then
    indent="$mwg_term_setfK- "
  fi

  mwg_echox_indent_stk[$mwg_echox_indent]=$mwg_echox_indent_text
  mwg_echox_indent=$((mwg_echox_indent+1))
  mwg_echox_indent_text="$mwg_echox_indent_text$indent$mwg_term_sgr0"
}

function echox_pop {
  if test "$mwg_echox_indent" -gt 0; then
    mwg_echox_indent=$((mwg_echox_indent-1))
    mwg_echox_indent_text=${mwg_echox_indent_stk[$mwg_echox_indent]}
  fi
}
