#!/bin/bash

function mydoc1 {
  awk '
    BEGIN{
      enum_max=0;
      mark_iter[0]="  * "
      mark_iter[1]="  + "
      mark_iter[2]="  - "
    }
  
    /^----$/{
      width=ENVIRON["COLUMNS"]
      if(width=="")width=80;
      width--;
      $0=""
      for(i=0;i<width;i++){
        $0=$0 "-"
      }
  
      print;
      next;
    }
  
    {
      if($0~/./)
        enumLevel=0;
  
      # :indentation
      if(match($0,/^([-#.+]+)[[:space:]]*/,m)){
        $0=substr($0,length(m[0])+1);
        iN=length(m[1]);
        lastChar=substr(m[1],iN);
  
        enumLevel=lastChar~/[#.]/?iN:iN-1;
        #print "dbg: enumLevel=" enumLevel ", enum_max=" enum_max
  
        if(lastChar=="#"){
          $0=" " ++enum[iN] ". " $0
          if(enum_max<iN)
            enum_max=iN;
          iN--;
        }else if(lastChar=="-"){
          $0=mark_iter[--iN%3] $0
        }else if(lastChar=="+"){
          $0=" \\_ " $0
          iN--;
        }
  
        for(;iN;iN--){
          lastChar=substr(m[1],iN,1);
          if(lastChar=="+")
            $0=" |  " $0;
          else
            $0="    " $0;
        }
        for(i=0;i<iN;i++)$0="    " $0
      }
  
      for(;enum_max>enumLevel;enum_max--)
        enum[enum_max]=0;
  
      # # _underline_ / *bold*
      # $0=gensub(/\y_([^_[:space:]]([^_]|_\y)*[^_[:space:]])_\y/   ,"[4m\\1[m","g",$0);
      # $0=gensub(/\B\*([^_[:space:]]([^_]|\*\y)*[^_[:space:]])\*\B/,"[1m\\1[m","g",$0);
  
      # bold/underline
      $0=gensub(/\[\*(([^*]|\*[^]])+)\*\]/,"[1m\\1[m","g",$0);
      $0=gensub(/\[\_(([^_]|\_[^]])+)\_\]/,"[4m\\1[m","g",$0);
  
      # color
      $0=gensub(/\[R\[(([^]]|\][^]])+)\]\]/,"[31m\\1[39m","g",$0);
      $0=gensub(/\[G\[(([^]]|\][^]])+)\]\]/,"[32m\\1[39m","g",$0);
      $0=gensub(/\[B\[(([^]]|\][^]])+)\]\]/,"[34m\\1[39m","g",$0);
      $0=gensub(/\[C\[(([^]]|\][^]])+)\]\]/,"[36m\\1[39m","g",$0);
      $0=gensub(/\[M\[(([^]]|\][^]])+)\]\]/,"[35m\\1[39m","g",$0);
      $0=gensub(/\[Y\[(([^]]|\][^]])+)\]\]/,"[33m\\1[39m","g",$0);
  
      print
    }
  '
}

if test $# -gt 0; then
  mydoc1 < "$1"
else
  mydoc1
fi
